training_configs:
  input_dir: /global/cfs/cdirs/m3443/usr/ameyat/hitgraphs/geometric/2p0
  artifact_dir: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
  batch_size: 64
  test_batch_size: 1000
  epochs: 100
  lr: 0.01
  gamma: 0.8
  step_size: 10

dataset_configs: 
  pt: 2

model_configs:
  n_input: 3
  n_hidden: 128
  n_layers: 5
  n_output: 1
  c_weight: 0.1
