# training_configs:
input_dir: /global/cfs/cdirs/m3443/usr/ameyat/hitgraphs/geometric/2p0
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: EuclideanTracking_SO(3)
model: EuclidNet
data_split: [1000, 100, 10]
batch_size: 4
gpus: [4]
nodes: 1

max_epochs: 100
lr: 0.001
factor: 0.8
patience: 30
warmup: 10
edge_cut: 0.5
weight: 0.5

# dataset_configs: 
pt: 2
truth_key: y

# model_configs:
n_input: 3
n_hidden: 32
n_layers: 3
n_graph_iters: 3
n_output: 1
c_weight: 0.1
equi_output: False
vector_dim: 3